### ISSUE TITLE
Mejora de visualización de resultados JSON

### ISSUE THREAD

**Issue by p431i7o** [melizeche/listaHu#2]
Se podría usar algún equivalente al JSON_PRETTY_PRINT de PHP ( http://php.net/json_encode )
Especialmente si se visita desde navegadores, puede ayudar a la lectura de humanos para el listado como el de http://listahu.org/api/v1/lista/

**Comment by melizeche** [comment]
Fixed in 908f24486be0aba38b662334915800105ea83b19
