### ISSUE TITLE
Interfaz bilingüe

### ISSUE THREAD

**Issue by fitojb** [melizeche/listaHu#3]
Me parece que el sitio web debería estar disponible en guaraní también, con un selector de idiomas en la parte superior. Desgraciadamente no hablo la lengua; de lo contrario, me ofrecería para hacer yo mismo la traducción.

**Comment by melizeche** [comment]
Lastimosamente yo tampoco así que por el momento no habrá ninguna novedad en cuanto a esto pero dejo el issue abierto por si alguien quiere colaborar
